### ISSUE TITLE
HP Omen Sequencer - with the same HOME-key issue, can you help to fix this one also?

### ISSUE THREAD

**Issue by nolimitse** [jingyu9575/remap-omen-key#2]
HP Omen Sequencer - with the same HOME-key issue, can you help to fix this one also?

https://www8.hp.com/us/en/displays-accessories/gaming/omen-sequencer.html

**Comment by jingyu9575** [comment]
Looks like this is an external keyboard. Does it require drivers to be installed? What's the current function of the OMEN key?

**Comment by nolimitse** [comment]
it works without drivers, still you have to install Omen Command Center via Windows Store.

what i remember is that the HOME-key is also remapped to Omen Command Center and not as a home key.

it doesnt work, what i've found to remap it to use it as home, if you could help i can try to assist with any files if you would like to help

**Comment by nolimitse** [comment]
when i check in the Command Center, it seems that the key is mapped as F24 and not 
HOME key

**Comment by jingyu9575** [comment]
> the key is mapped as F24

In this case I suggest try to remap F24 to Home in the system.

Please test [these scripts](https://github.com/jingyu9575/remap-omen-key/files/3198862/attachments.zip):

* Run KeyHistory.exe. In the window, press OMEN then F5. Check if the log shows F24 and if the Command Center is opened.
* Quit KeyHistory in the system tray and run F24toHome.exe. Press OMEN in a text box. Check if it is correctly changed to home, and if the Command Center is still opened.

**Comment by nolimitse** [comment]
thank you, it worked. can you add this to github?

**Comment by nolimitse** [comment]
and is there any fix you can put this in registry or something more convenient? what is the best solution.

**Comment by jingyu9575** [comment]
The information is added to the guide. 

There is a way to [remap keys using the registry](https://www.howtogeek.com/howto/windows-vista/disable-caps-lock-key-in-windows-vista/), but it is complicated. There is also a tool [SharpKeys](https://github.com/randyrants/sharpkeys) that helps edit the registry remap.
![图片](https://user-images.githubusercontent.com/8923139/58118028-94e8bb00-7c32-11e9-989f-be1a5ed2d7cd.png)

I would personally use the script, since it does not require restart and can be disabled at any time, by terminating the process. Another build of F24ToHome.exe without the tray icon is [here](https://github.com/jingyu9575/remap-omen-key/releases).
