### ISSUE TITLE
"HP System Event" does not use registry path - could not define any exe to be launched

### ISSUE THREAD

**Issue by Stern77** [jingyu9575/remap-omen-key#9]
I downloaded "HP System Event" from https://ftp.hp.com/pub/softpaq/sp70001-70500/sp70439.exe and installed it.
The sp70439.exe created the folder "C:\SWSetup\SP70439" where it put installers like "HPSystemEventUtility.msi" which are called to install the files under "C:\Program Files (x86)\Hewlett-Packard\HP System Event\".
After the installer finishes there is nothing happening. Not even HPMSGSVC.exe is started. So I start it by double click on it. I would expect either the HPMSGSVC.exe or the installer must have created the registry path "HKEY_CURRENT_USER\Software\HP\HP System Event\Bezel Button\8613" but all I can find is...
"Computer\HKEY_CURRENT_USER\Software\Hewlett-Packard"
"Computer\HKEY_CURRENT_USER\Software\Hewlett-Packard\HPDIA"
"Computer\HKEY_CURRENT_USER\Software\Hewlett-Packard\HPSF"
"Computer\HKEY_CURRENT_USER\Software\HP"
"Computer\HKEY_CURRENT_USER\Software\HP\HPDIA"
"Computer\HKEY_CURRENT_USER\Software\HP\Hpjumpstartappss"
"Computer\HKEY_CURRENT_USER\Software\HP\Hpjumpstartappss"
"Computer\HKEY_CURRENT_USER\Software\HP\Theme Control"
"Computer\HKEY_CURRENT_USER\Software\HP PC Hardware Diagnostics Windows"

The "..\HP System Event\Bezel Button\8613" is not even created after "HPMSGSVC.exe" runs and I pressed the omen key :(

When I create the path on my own the "HPMSGSVC.exe" does not care about it.

**Comment by jingyu9575** [comment]
I'm using a different version; try this instead: http://ftp.hp.com/pub/softpaq/sp81001-81500/sp81404.exe

**Comment by Stern77** [comment]
Thank you.
I figured out that my version uses
HKEY_CURRENT_USER\Software\Hewlett-Packard\HP System Event\Bezel Button\8613
instead.
It worked only after I restarted my computer. I don't know why but now it works :)))

But it takes about 2 seconds after omen key is pressed until I could see the reaction of the active application. So it is not quiet the same behaviour like having a native home button. But better than none..

Thank you so much for your work....

PS: If you know how to speed this up that would be awesome..

**Comment by jingyu9575** [comment]
> If you know how to speed this up

I am now using the different method ([the custom-client branch](https://github.com/jingyu9575/remap-omen-key/tree/custom-client)) which seems faster. 

Update to sp81404, and download [custom-client.exe](https://github.com/jingyu9575/remap-omen-key/releases) to "C:\Program Files (x86)\HP\HP System Event". Stop and disable HPMSGSVC.exe, and auto-start my exe file instead.

However, the file needs to be signed to work, and the user must add the signature to the "Trusted people" store (Right-click the exe -> Properties -> Digital signature -> Details -> View signature -> Install). This is complicated, and its security impact is that your computer will now view my signed executables as "verified from @jingyu9575" instead of unsigned.

The advantage is that it doesn't require launching a new exe every time you press OMEN, so it may be faster.
